name: Docker Image CI

on:
  push:
    branches: [ ci3 ]
  pull_request:
    branches: [ ci3 ]
env:
  DOCKER_USERNAME: wincognito
  DOCKER_TOKEN_OR_PASSWORD: "${{ secrets.PUSH1 }}"
  REPO: wincognito/caddy-reverse-proxy

permissions:
  contents: write


jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Fetch all commits
        fetch-depth: 0
        # ref: ci3

    - name: Get Package
      # You may pin to the exact commit or the version.
      # uses: mstksg/get-package@4eda30bb5c6ac62c0f3921dd5884b6ef8fc89ab2
      uses: mstksg/get-package@v1
      with:
        apt-get: buildah podman


    - name: Run script
      run: ./publish.sh
      shell: bash


