name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_USERNAME: wincognito
  REPO: wincognito/caddy-reverse-proxy

permissions:
  contents: write


jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Fetch all commits
        fetch-depth: 0
