name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_USERNAME: wincognito
  REPO: wincognito/caddy-reverse-proxy

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Fetch all commits
        fetch-depth: 0


    - name: Set environment variables
      run: |
        cat >> $GITHUB_ENV << EOF
        VERSION=${GITHUB_REF##*/}
        EOF


    # https://github.com/marketplace/actions/git-semantic-version
    - name: Semantic versioning
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefix: "v"
        major_pattern: "MAJOR:"
        minor_pattern: "minor:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"


    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.PUSH1 }}


    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        tags: "${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }},${{ env.VERSION }}"


    - name: Create prerelease
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: true
        release_name: ${{ steps.versioning.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md


    - name: Create release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.versioning.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
